name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *" # update otomatis tiap 6 jam
  workflow_dispatch: # bisa di-trigger manual dari tab Actions
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG (neon & matrix theme)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-neon.svg?palette=%230A0E27,%230072FF,%2300C6FF,%2300F0FF,%238FE9FF
            dist/github-contribution-grid-snake-matrix.svg?palette=%23050505,%23003b00,%23008f11,%2300ff41,%23a3ffb2

      - name: Push generated SVG to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
